import type { AlphabetLetter } from './types';

export const alphabet: AlphabetLetter[] = [
  { letter: 'A', word: 'Apple', imageId: 'alphabet-a', youtubeVideoId: 'U3Lz_S1dyvQ' },
  { letter: 'B', word: 'Ball', imageId: 'alphabet-b', youtubeVideoId: 'wZ3z-d4i3pQ' },
  { letter: 'C', word: 'Cat', imageId: 'alphabet-c', youtubeVideoId: '7y09w23aOoA' },
  { letter: 'D', word: 'Dog', imageId: 'alphabet-d', youtubeVideoId: 'J4p4ln78D0M' },
  { letter: 'E', word: 'Elephant', imageId: 'alphabet-e', youtubeVideoId: 'Zp2F4iA5A-g' },
  { letter: 'F', word: 'Fish', imageId: 'alphabet-f', youtubeVideoId: 'RX3S3vI2grg' },
  { letter: 'G', word: 'Guitar', imageId: 'alphabet-g', youtubeVideoId: 'k42oVWE_F-M' },
  { letter: 'H', word: 'Hat', imageId: 'alphabet-h', youtubeVideoId: 'YQvqsWJ2x5s' },
  { letter: 'I', word: 'Igloo', imageId: 'alphabet-i', youtubeVideoId: 'o_aAoqhLges' },
  { letter: 'J', word: 'Jellyfish', imageId: 'alphabet-j', youtubeVideoId: 'c2bOC5DxkZI' },
  { letter: 'K', word: 'Kite', imageId: 'alphabet-k', youtubeVideoId: 'C-T3Nd2p30s' },
  { letter: 'L', word: 'Lion', imageId: 'alphabet-l', youtubeVideoId: 'f0X5m4aKk0Y' },
  { letter: 'M', word: 'Mouse', imageId: 'alphabet-m', youtubeVideoId: 'SwnrS2sXo-I' },
  { letter: 'N', word: 'Nest', imageId: 'alphabet-n', youtubeVideoId: 'kLaa97N6k1g' },
  { letter: 'O', word: 'Octopus', imageId: 'alphabet-o', youtubeVideoId: 'zanmleQ8M7g' },
  { letter: 'P', word: 'Penguin', imageId: 'alphabet-p', youtubeVideoId: '1QxGvtnN7TE' },
  { letter: 'Q', word: 'Queen', imageId: 'alphabet-q', youtubeVideoId: 'lq5uzgQq0so' },
  { letter: 'R', word: 'Robot', imageId: 'alphabet-r', youtubeVideoId: 'cqidD92nL8A' },
  { letter: 'S', word: 'Sun', imageId: 'alphabet-s', youtubeVideoId: 'aDP3sioe02I' },
  { letter: 'T', word: 'Turtle', imageId: 'alphabet-t', youtubeVideoId: 'LjVd-1c3P0c' },
  { letter: 'U', word: 'Umbrella', imageId: 'alphabet-u', youtubeVideoId: 'L2sAAa1z9-c' },
  { letter: 'V', word: 'Volcano', imageId: 'alphabet-v', youtubeVideoId: 'bocyXxWLa0I' },
  { letter: 'W', word: 'Whale', imageId: 'alphabet-w', youtubeVideoId: 's3pQ2239mP0' },
  { letter: 'X', word: 'Xylophone', imageId: 'alphabet-x', youtubeVideoId: 'pounJeE4WvA' },
  { letter: 'Y', word: 'Yarn', imageId: 'alphabet-y', youtubeVideoId: 'gAgCj1s2oR8' },
  { letter: 'Z', word: 'Zebra', imageId: 'alphabet-z', youtubeVideoId: 'RjdbHW6-fgI' },
];
